from .contact import Contact
from .address import Address
from .email import Email
from .name import Name
from .organization import Organization
from .phone import Phone
from .url import URL
from . import address
from . import email
from . import name
from . import organization
from . import phone
from . import url